### ISSUE TITLE
Cannot add webhook for code-paw/bling-souk

### ISSUE THREAD

**Issue by baishali-ghosh** [code-paw/bling-souq#6]
Admin access is required and I am unable to generate a web hook by clicking on the button in the lower left.

**Comment by baishali-ghosh** [comment]
![screenshot 2016-07-20 19 43 36](https://cloud.githubusercontent.com/assets/3686662/16989591/6f254042-4eb2-11e6-97ee-8220ba803ab3.png)

**Comment by kunagpal** [comment]
Both of us have admin access by default. There is a pre-existing web-hook for waffle [here](https://github.com/code-paw/bling-souq/settings/hooks), you might want to try resetting it.

**Comment by kunagpal** [comment]
The should have been fixed now, if the error modal shows up at the bottom of the project board, opt to not see it again.
